#!/usr/bin/env python3
"""Generate views/pages_catalog.xml from data/m6_catalog_source.json.

The source JSON was extracted from the original builder pages in eot_main
(views 1566 "آزمون-روانشناسی" and 1570 "یادگیری-خودیار-روانشناسی") during
milestone 6, so the 36 assessment cards and 74 course cards keep the exact
wording the owner wrote. Re-run after editing the JSON:

    python3 scripts/gen_catalogs.py

Format:
  "a": [name, items, dims, description, audience, time, "cat|cat", scored]
  "c": [family, name, description, "N XP"]
"""
import json
import os
from xml.sax.saxutils import escape, quoteattr

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FA = str.maketrans("0123456789", "۰۱۲۳۴۵۶۷۸۹")
FAMILY = {
    "assessment": "بر پایه ارزیابی",
    "books": "مطالعه هدایت‌شده کتاب",
    "articles": "مسیرهای موضوعی مقالات",
    "glossary": "تسلط مفهومی فرهنگنامه",
    "live": "مکمل کلاس‌های زنده",
    "internship": "مسیر حرفه‌ای کارورزی",
}


def fa(s):
    return escape(str(s).translate(FA))


def assessment(a):
    name, items, dims, desc, aud, time, cats, scored = a
    pills = ['<span class="eot-pill eot-pill-teal">رایگان</span>']
    if scored:
        pills.append('<span class="eot-pill eot-pill-teal">تفسیر امتیاز</span>')
    pills += ['<span class="eot-pill eot-pill-sand">%s</span>' % escape(c) for c in cats.split("|")]
    return f"""
            <article class="eot-card eot-assess" data-eot-item="" data-cat={quoteattr(cats)}>
                <div class="eot-pills">{''.join(pills)}</div>
                <h3>{escape(name)}</h3>
                <p>{fa(desc)}</p>
                <dl class="eot-meta eot-meta-4">
                    <div><dt>تعداد سؤال</dt><dd>{fa(items)}</dd></div>
                    <div><dt>ابعاد سنجش</dt><dd>{fa(dims)}</dd></div>
                    <div><dt>مخاطب</dt><dd>{escape(aud)}</dd></div>
                    <div><dt>زمان تقریبی</dt><dd>{fa(time.replace('حدود ', ''))}</dd></div>
                </dl>
                <span class="eot-btn eot-btn-soon">شروع آنلاین به‌زودی</span>
            </article>"""


def course(c):
    fam, name, desc, xp = c
    return f"""
            <article class="eot-card eot-course" data-eot-item="" data-family="{fam}">
                <div class="eot-course-top"><span>{FAMILY[fam]}</span><span>{fa(xp)}</span></div>
                <h3>{escape(name)}</h3>
                <p>{fa(desc)}</p>
                <span class="eot-btn eot-btn-soon">به‌زودی فعال می‌شود</span>
            </article>"""


def main():
    data = json.load(open(os.path.join(ROOT, "data", "m6_catalog_source.json"), encoding="utf-8"))
    out = ['<?xml version="1.0" encoding="utf-8"?>', "<odoo>",
           "    <!-- GENERATED by scripts/gen_catalogs.py from data/m6_catalog_source.json - do not edit by hand. -->",
           '    <template id="catalog_assessments" name="EOT catalog: assessments">']
    out += [assessment(a) for a in data["a"]]
    out += ["    </template>", '    <template id="catalog_courses" name="EOT catalog: courses">']
    out += [course(c) for c in data["c"]]
    out += ["    </template>", "</odoo>", ""]
    path = os.path.join(ROOT, "views", "pages_catalog.xml")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("wrote", path, len(data["a"]), "assessments,", len(data["c"]), "courses")


if __name__ == "__main__":
    main()
